# POST  http://localhost:3001/login
# Content-Type: application/json
# # authorization: Bearer 3211f78e-1adc-4dd6-9d36-ca4b866409c2

# { 
#    "email": "test1", 
#    "password": "test1"
# }

# POST http://localhost:3001/api/login
# Content-Type: application/json

# {
#     "email":"alextay0naruto@gmail.com",
#     "password": "asdasd"
# }


# GET http://localhost:3001/api/products/get/1
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywicGFzc3dvcmQiOiIkMmIkMTAkM3kwSGxPaC9DaXlxRHZFa2RlcUltZUMvMmlIelNEc1dUMzRFVENxeXppTVJMYW9qbXF1Z2EiLCJpYXQiOjE2MDE1ODQxMzksImV4cCI6MTYwMTU4NzczOX0.EVny7MxgECcbCtHR_uJFqE-KlBlN5zyKgrfS4B-KGk8

POST http://localhost:3001/api/products/update_productvar
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwicGFzc3dvcmQiOiIkMmIkMTAkbU90SFFCRnRWb0EvS3RzM3h2TzBHdVF4MkwwYmlBSklEazhUaGlqdkxNanBiNnRDR3Vyby4iLCJpYXQiOjE2MDE3NDEyMjcsImV4cCI6MTYwMTc0NDgyN30.fwf__x6YSvJwCyjhNbVyOblJNNxDy_x89Q1YjTco__4

{
    "product_id":1,
    "brand":"sss"
}